### ISSUE TITLE
How to paginate contacts?

### ISSUE THREAD

**Issue by tycooperaow** [jpetrucciani/hubspot3#89] opened 2020-02-12 01:11 UTC
When I get the contact list from hub sport it gets them in a large dataset since the project I'm working on has a lot of contacts like over 2000. How do I paginate this?

```
@api.route("/hubspot/contacts/")
@cross_origin(supports_credentials=True)
def getHubspotContacts():
    """Gets a list of the clients we have in hubspot"""
    API_KEY = "api-key"
    hb_client = Hubspot3(api_key=API_KEY)

    contacts = hb_client.contacts.get_all()
    # display = contacts[range_val:(range_val+20)]
    return jsonify(contacts)
```

**Comment by jpetrucciani** [comment] 2020-02-12 13:59
Duplicate of #84

**Closed by jpetrucciani** 2020-02-12 13:59 UTC
